bpf:
  masquerade: "true"
cluster:
  id: 0
  name: goldielock-cnis-cilium
egressMasqueradeInterfaces: eth0
enable-ipv4-masquerade: "true"
encryption:
  nodeEncryption: false
eni:
  enabled: true
hubble:
  enabled: "true"
  metrics:
    enableOpenMetrics: "true"
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
ipMasqAgent:
  config:
    masqLinkLocal: "false"
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  enabled: "true"
ipam: 
  mode: kubernetes
k8sServiceHost: 172.20.0.1
k8sServicePort: "443"
kubeProxyReplacement: strict
nodeinit:
  enabled: true
operator:
  prometheus:
    enabled: "true"
  replicas: 1
prometheus:
  enabled: "true"
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
tunnel: disabled
