cidr: 10.0.0.0/16
bootstrap_extra_args: |
  # The admin host container provides SSH access and runs with "superpowers".
  # It is disabled by default, but can be disabled explicitly.
  [settings.host-containers.admin]
  enabled = false

  # The control host container provides out-of-band access via SSM.
  # It is enabled by default, and can be disabled if you do not expect to use SSM.
  # This could leave you with no way to access the API and change settings on an existing node!
  [settings.host-containers.control]
  enabled = true

  [settings.kubernetes.node-labels]
  "goldie" = "enabled"
  ingress = "allowed"

  [settings.kubernetes.node-taints]
  "node.cilium.io/agent-not-ready" = "true:NoExecute"
cluster_addons:
  # coredns:
  #   resolve_conflicts: "OVERWRITE"
  #   addon_version: "v1.8.7-eksbuild.1"
  #
  kube-proxy: {}
  # vpc-cni:
  #   addon_version: "v1.11.4-eksbuild.1"
  #   resolve_conflicts: "OVERWRITE"
  #
  