apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-node-app
  labels:
    app: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
        bobinette: pull
    spec:
      containers:
      - name: vulnerable-container
        image: nginx:1.16
        ports:
        - containerPort: 3000
