sync:
  ingresses:
    enabled: true
  nodes:
    enabled: true    
    nodeSelector: "node.kubernetes.io/instance-type=t3.medium"
    enableScheduler: true

defaultImageRegistry: 955480398230.dkr.ecr.eu-west-1.amazonaws.com/

isolation:
  enabled: false

  podSecurityStandard: baseline

  resourceQuota:
    enabled: true
    quota:
      requests.cpu: 10
      requests.memory: 20Gi
      requests.storage: "100Gi"
      requests.ephemeral-storage: 60Gi
      limits.cpu: 20
      limits.memory: 40Gi
      limits.ephemeral-storage: 160Gi
      services.nodeports: 1
      services.loadbalancers: 2
      count/endpoints: 40
      count/pods: 20
      count/services: 20
      count/secrets: 100
      count/configmaps: 100
      count/persistentvolumeclaims: 20
    scopeSelector:
      matchExpressions:
    scopes:

  limitRange:
    enabled: true
    default:
      ephemeral-storage: 8Gi
      memory: 512Mi
      cpu: "1"
    defaultRequest:
      ephemeral-storage: 3Gi
      memory: 128Mi
      cpu: 100m

  # networkPolicy:
  #   enabled: true
  #   outgoingConnections:
  #     ipBlock:
  #       cidr: 0.0.0.0/0
  #       except:
  #         - 100.64.0.0/10
  #         - 127.0.0.0/8
  #         - 10.0.0.0/8
  #         - 172.16.0.0/12
  #         - 192.168.0.0/16