kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  typhaMetricsPort: 9093
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
  registry: 955480398230.dkr.ecr.eu-west-1.amazonaws.com